### ISSUE TITLE
Can you explain why this module is needed?

### ISSUE THREAD

**Issue by vvo** [evbots/serverless-pg#4]
Hey thanks for the module. I am trying to find the best practices as for serverless/lamba/zeit connection to postgres (rds) but it’s not very well documented. You seem to have expertise on this so I would gladly learn from you, thanks!

**Comment by evbots** [comment]
Hey @vvo, i've been planning to put some logic in here that reuses postgres connections across lambda invocations. Just haven't gotten around to it yet. Currently it just provides a way to access a singleton postgres connection export, and there's a bit of code that provides some guarantees that you reuse the current active connection instead of creating multiple connections at once (during the span of a single lambda invocation).

**Comment by vvo** [comment]
Thanks!
